version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.hibernate.orm:hibernate-core"
        versions: [ ">=7" ]
      - dependency-name: "org.hibernate.validator:hibernate-validator"
        versions: [ ">=9" ]
      - dependency-name: "org.glassfish.jersey:*"
        versions: [ ">= 4" ]
      - dependency-name: "jakarta.servlet:jakarta.servlet-api"
        versions: [ ">=6.1" ]
      - dependency-name: "jakarta.validation:jakarta.validation-api"
        versions: [ ">=3.1" ]
    groups:
      dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "jakarta.servlet:jakarta.servlet-api"
          - "jakarta.validation:jakarta.validation-api"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
      semver-patch-days: 5
      semver-minor-days: 14
      semver-major-days: 30
      exclude:
        - "org.kiwiproject:*"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps)"
