version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "org.glassfish.jersey:*"
          - "jakarta.validation:jakarta.validation-api"
          - "ch.qos.logback:*"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
